name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: python3-rpm
        version: 1.0
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - uses: cloudposse/github-action-pre-commit@v2.1.2
